server.servlet.context-path=/api
springdoc.api-docs.path=/api-docs
security.public.paths=/public,/api/api-docs,/api-docs
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://keycloak.roboter5123.com/realms/robolock
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://keycloak.roboter5123.com/realms/robolock/protocol/openid-connect/certs
spring.datasource.url=${database_url}
spring.datasource.username=${database_username}
spring.datasource.password=${database_password}



