# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Stable

on:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: maven:3.9-eclipse-temurin-21
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github-deploy # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build with Maven
        run: mvn -B clean install -s $GITHUB_WORKSPACE/.github/workflows/settings.xml --file pom.xml
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}

      - name: Deploy OpenAPI Client to Gitea Maven Repo
        run: mvn deploy --file target/generated-sources/java/pom.xml -DaltDeploymentRepository=gitea-deploy::default::https://gitea.roboter5123.com/api/packages/${{ gitea.repository_owner }}/maven -s ./.gitea/workflows/settings.xml
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -s $GITHUB_WORKSPACE/.github/workflows/settings.xml
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: ${{ github.event.repository.name }}
          tags: latest
          registry: ghcr.io
          dockerfile: Dockerfile
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ACCESS_TOKEN }}